"""
LVIS 1203カテゴリ(YOLOEプロンプトフリーの内蔵語彙)の英→日対訳。

キーは LVIS 名の「最初の同義語」を小文字化したもの
(例 "aerosol can/spray can" -> キー "aerosol can")。
labels_ja.to_ja() が入力ラベルを "/" で分割し最初の語で照合するため、
モデルがフル文字列・最初の同義語のどちらを出しても一致する。

ベストエフォートの対訳。誤り・好みに応じて自由に修正・追記してよい。
"""
from __future__ import annotations

LVIS_JA: dict[str, str] = {
    "aerosol can": "スプレー缶",
    "air conditioner": "エアコン",
    "airplane": "飛行機",
    "alarm clock": "目覚まし時計",
    "alcohol": "アルコール飲料",
    "alligator": "ワニ",
    "almond": "アーモンド",
    "ambulance": "救急車",
    "amplifier": "アンプ",
    "anklet": "アンクレット",
    "antenna": "アンテナ",
    "apple": "りんご",
    "applesauce": "アップルソース",
    "apricot": "あんず",
    "apron": "エプロン",
    "aquarium": "水槽",
    "arctic": "防水靴",
    "armband": "腕章",
    "armchair": "肘掛け椅子",
    "armoire": "衣装だんす",
    "armor": "鎧",
    "artichoke": "アーティチョーク",
    "trash can": "ゴミ箱",
    "ashtray": "灰皿",
    "asparagus": "アスパラガス",
    "atomizer": "噴霧器",
    "avocado": "アボカド",
    "award": "賞",
    "awning": "日よけ",
    "ax": "斧",
    "baboon": "ヒヒ",
    "baby buggy": "ベビーカー",
    "basketball backboard": "バックボード",
    "backpack": "リュック",
    "handbag": "ハンドバッグ",
    "suitcase": "スーツケース",
    "bagel": "ベーグル",
    "bagpipe": "バグパイプ",
    "baguet": "バゲット",
    "bait": "釣り餌",
    "ball": "ボール",
    "ballet skirt": "チュチュ",
    "balloon": "風船",
    "bamboo": "竹",
    "banana": "バナナ",
    "band aid": "絆創膏",
    "bandage": "包帯",
    "bandanna": "バンダナ",
    "banjo": "バンジョー",
    "banner": "横断幕",
    "barbell": "バーベル",
    "barge": "はしけ",
    "barrel": "樽",
    "barrette": "バレッタ",
    "barrow": "手押し車",
    "baseball base": "ベース",
    "baseball": "野球ボール",
    "baseball bat": "バット",
    "baseball cap": "野球帽",
    "baseball glove": "グローブ",
    "basket": "かご",
    "basketball": "バスケットボール",
    "bass horn": "チューバ",
    "bat": "コウモリ",
    "bath mat": "バスマット",
    "bath towel": "バスタオル",
    "bathrobe": "バスローブ",
    "bathtub": "浴槽",
    "batter": "生地",
    "battery": "電池",
    "beachball": "ビーチボール",
    "bead": "ビーズ",
    "bean curd": "豆腐",
    "beanbag": "ビーズクッション",
    "beanie": "ニット帽",
    "bear": "熊",
    "bed": "ベッド",
    "bedpan": "差し込み便器",
    "bedspread": "ベッドカバー",
    "cow": "牛",
    "beef": "牛肉",
    "beeper": "ポケベル",
    "beer bottle": "ビール瓶",
    "beer can": "ビール缶",
    "beetle": "カブトムシ",
    "bell": "鐘",
    "bell pepper": "ピーマン",
    "belt": "ベルト",
    "belt buckle": "ベルトのバックル",
    "bench": "ベンチ",
    "beret": "ベレー帽",
    "bib": "よだれかけ",
    "bible": "聖書",
    "bicycle": "自転車",
    "visor": "バイザー",
    "billboard": "看板",
    "binder": "バインダー",
    "binoculars": "双眼鏡",
    "bird": "鳥",
    "birdfeeder": "餌台",
    "birdbath": "鳥の水浴び場",
    "birdcage": "鳥かご",
    "birdhouse": "巣箱",
    "birthday cake": "バースデーケーキ",
    "birthday card": "バースデーカード",
    "pirate flag": "海賊旗",
    "black sheep": "黒い羊",
    "blackberry": "ブラックベリー",
    "blackboard": "黒板",
    "blanket": "毛布",
    "blazer": "ブレザー",
    "blender": "ミキサー",
    "blimp": "飛行船",
    "blinker": "ウインカー",
    "blouse": "ブラウス",
    "blueberry": "ブルーベリー",
    "gameboard": "ゲーム盤",
    "boat": "船",
    "bob": "浮き",
    "bobbin": "糸巻き",
    "bobby pin": "ヘアピン",
    "boiled egg": "ゆで卵",
    "bolo tie": "ボロタイ",
    "deadbolt": "かんぬき錠",
    "bolt": "ボルト",
    "bonnet": "ボンネット帽",
    "book": "本",
    "bookcase": "本棚",
    "booklet": "小冊子",
    "bookmark": "しおり",
    "boom microphone": "ブームマイク",
    "boot": "ブーツ",
    "bottle": "ボトル",
    "bottle opener": "栓抜き",
    "bouquet": "花束",
    "bow": "弓",
    "bow-tie": "蝶ネクタイ",
    "bowl": "ボウル",
    "pipe bowl": "パイプの火皿",
    "bowler hat": "山高帽",
    "bowling ball": "ボウリングの球",
    "box": "箱",
    "boxing glove": "ボクシンググローブ",
    "suspenders": "サスペンダー",
    "bracelet": "ブレスレット",
    "brass plaque": "真鍮の銘板",
    "brassiere": "ブラジャー",
    "bread-bin": "パン入れ",
    "bread": "パン",
    "breechcloth": "腰布",
    "bridal gown": "ウェディングドレス",
    "briefcase": "ブリーフケース",
    "broccoli": "ブロッコリー",
    "broach": "ブローチ",
    "broom": "ほうき",
    "brownie": "ブラウニー",
    "brussels sprouts": "芽キャベツ",
    "bubble gum": "風船ガム",
    "bucket": "バケツ",
    "horse buggy": "馬車",
    "horned cow": "角のある牛",
    "bulldog": "ブルドッグ",
    "bulldozer": "ブルドーザー",
    "bullet train": "新幹線",
    "bulletin board": "掲示板",
    "bulletproof vest": "防弾チョッキ",
    "bullhorn": "メガホン",
    "bun": "丸パン",
    "bunk bed": "二段ベッド",
    "buoy": "ブイ",
    "burrito": "ブリトー",
    "bus": "バス",
    "business card": "名刺",
    "butter": "バター",
    "butterfly": "蝶",
    "button": "ボタン",
    "cab": "タクシー",
    "cabana": "海辺の小屋",
    "cabin car": "車掌車",
    "cabinet": "キャビネット",
    "locker": "ロッカー",
    "cake": "ケーキ",
    "calculator": "電卓",
    "calendar": "カレンダー",
    "calf": "子牛",
    "camcorder": "ビデオカメラ",
    "camel": "ラクダ",
    "camera": "カメラ",
    "camera lens": "カメラレンズ",
    "camper": "キャンピングカー",
    "can": "缶",
    "can opener": "缶切り",
    "candle": "ろうそく",
    "candle holder": "ろうそく立て",
    "candy bar": "チョコバー",
    "candy cane": "キャンディケーン",
    "walking cane": "杖",
    "canister": "キャニスター",
    "canoe": "カヌー",
    "cantaloup": "メロン",
    "canteen": "水筒",
    "cap": "帽子",
    "bottle cap": "瓶のふた",
    "cape": "ケープ",
    "cappuccino": "カプチーノ",
    "car": "車",
    "railcar": "鉄道車両",
    "elevator car": "エレベーターのかご",
    "car battery": "カーバッテリー",
    "identity card": "身分証",
    "card": "カード",
    "cardigan": "カーディガン",
    "cargo ship": "貨物船",
    "carnation": "カーネーション",
    "horse carriage": "馬車",
    "carrot": "にんじん",
    "tote bag": "トートバッグ",
    "cart": "カート",
    "carton": "紙箱",
    "cash register": "レジ",
    "casserole": "キャセロール",
    "cassette": "カセット",
    "cast": "ギプス",
    "cat": "猫",
    "cauliflower": "カリフラワー",
    "cayenne": "カイエンペッパー",
    "cd player": "CDプレーヤー",
    "celery": "セロリ",
    "cellular telephone": "携帯電話",
    "chain mail": "鎖かたびら",
    "chair": "椅子",
    "chaise longue": "寝椅子",
    "chalice": "聖杯",
    "chandelier": "シャンデリア",
    "chap": "チャップス",
    "checkbook": "小切手帳",
    "checkerboard": "チェッカー盤",
    "cherry": "さくらんぼ",
    "chessboard": "チェス盤",
    "chicken": "鶏",
    "chickpea": "ひよこ豆",
    "chili": "唐辛子",
    "chime": "チャイム",
    "chinaware": "陶磁器",
    "crisp": "ポテトチップス",
    "poker chip": "ポーカーチップ",
    "chocolate bar": "板チョコ",
    "chocolate cake": "チョコレートケーキ",
    "chocolate milk": "チョコレートミルク",
    "chocolate mousse": "チョコレートムース",
    "choker": "チョーカー",
    "chopping board": "まな板",
    "chopstick": "箸",
    "christmas tree": "クリスマスツリー",
    "slide": "滑り台",
    "cider": "シードル",
    "cigar box": "葉巻入れ",
    "cigarette": "タバコ",
    "cigarette case": "タバコケース",
    "cistern": "貯水タンク",
    "clarinet": "クラリネット",
    "clasp": "留め金",
    "cleansing agent": "洗剤",
    "cleat": "クリート",
    "clementine": "クレメンタイン",
    "clip": "クリップ",
    "clipboard": "クリップボード",
    "clippers": "園芸ばさみ",
    "cloak": "マント",
    "clock": "時計",
    "clock tower": "時計塔",
    "clothes hamper": "洗濯かご",
    "clothespin": "洗濯ばさみ",
    "clutch bag": "クラッチバッグ",
    "coaster": "コースター",
    "coat": "コート",
    "coat hanger": "ハンガー",
    "coatrack": "コート掛け",
    "cock": "雄鶏",
    "cockroach": "ゴキブリ",
    "cocoa": "ココア",
    "coconut": "ココナッツ",
    "coffee maker": "コーヒーメーカー",
    "coffee table": "コーヒーテーブル",
    "coffeepot": "コーヒーポット",
    "coil": "コイル",
    "coin": "硬貨",
    "colander": "ザル",
    "coleslaw": "コールスロー",
    "coloring material": "塗り絵用具",
    "combination lock": "ダイヤル錠",
    "pacifier": "おしゃぶり",
    "comic book": "漫画本",
    "compass": "コンパス",
    "computer keyboard": "キーボード",
    "condiment": "調味料",
    "cone": "コーン(三角)",
    "control": "コントローラー",
    "convertible": "オープンカー",
    "sofa bed": "ソファベッド",
    "cooker": "調理器",
    "cookie": "クッキー",
    "cooking utensil": "調理器具",
    "cooler": "クーラーボックス",
    "cork": "コルク",
    "corkboard": "コルクボード",
    "corkscrew": "コルク抜き",
    "edible corn": "トウモロコシ",
    "cornbread": "コーンブレッド",
    "cornet": "コルネット",
    "cornice": "カーテンボックス",
    "cornmeal": "コーンミール",
    "corset": "コルセット",
    "costume": "衣装",
    "cougar": "ピューマ",
    "coverall": "つなぎ服",
    "cowbell": "カウベル",
    "cowboy hat": "カウボーイハット",
    "crab": "カニ",
    "crabmeat": "カニ肉",
    "cracker": "クラッカー",
    "crape": "クレープ",
    "crate": "木箱",
    "crayon": "クレヨン",
    "cream pitcher": "クリーム入れ",
    "crescent roll": "クロワッサン",
    "crib": "ベビーベッド",
    "crock pot": "スロークッカー",
    "crossbar": "クロスバー",
    "crouton": "クルトン",
    "crow": "カラス",
    "crowbar": "バール",
    "crown": "王冠",
    "crucifix": "十字架",
    "cruise ship": "クルーズ船",
    "police cruiser": "パトカー",
    "crumb": "パンくず",
    "crutch": "松葉杖",
    "cub": "動物の子",
    "cube": "立方体",
    "cucumber": "きゅうり",
    "cufflink": "カフスボタン",
    "cup": "カップ",
    "trophy cup": "トロフィー",
    "cupboard": "戸棚",
    "cupcake": "カップケーキ",
    "hair curler": "ヘアカーラー",
    "curling iron": "ヘアアイロン",
    "curtain": "カーテン",
    "cushion": "クッション",
    "cylinder": "円筒",
    "cymbal": "シンバル",
    "dagger": "短剣",
    "dalmatian": "ダルメシアン",
    "dartboard": "ダーツの的",
    "date": "ナツメヤシの実",
    "deck chair": "デッキチェア",
    "deer": "鹿",
    "dental floss": "デンタルフロス",
    "desk": "机",
    "detergent": "洗剤",
    "diaper": "おむつ",
    "diary": "日記帳",
    "die": "サイコロ",
    "dinghy": "小舟",
    "dining table": "テーブル",
    "tux": "タキシード",
    "dish": "皿",
    "dish antenna": "パラボラアンテナ",
    "dishrag": "ふきん",
    "dishtowel": "布巾",
    "dishwasher": "食洗機",
    "dishwasher detergent": "食洗機用洗剤",
    "dispenser": "ディスペンサー",
    "diving board": "飛び込み台",
    "dixie cup": "紙コップ",
    "dog": "犬",
    "dog collar": "犬の首輪",
    "doll": "人形",
    "dollar": "ドル紙幣",
    "dollhouse": "ドールハウス",
    "dolphin": "イルカ",
    "domestic ass": "ロバ",
    "doorknob": "ドアノブ",
    "doormat": "玄関マット",
    "donut": "ドーナツ",
    "dove": "ハト",
    "dragonfly": "トンボ",
    "drawer": "引き出し",
    "underdrawers": "下着のパンツ",
    "dress": "ドレス",
    "dress hat": "シルクハット",
    "dress suit": "礼服",
    "dresser": "化粧だんす",
    "drill": "ドリル",
    "drone": "ドローン",
    "dropper": "スポイト",
    "drum": "ドラム",
    "drumstick": "ドラムスティック",
    "duck": "アヒル",
    "duckling": "アヒルの子",
    "duct tape": "ガムテープ",
    "duffel bag": "ダッフルバッグ",
    "dumbbell": "ダンベル",
    "dumpster": "大型ゴミ容器",
    "dustpan": "ちりとり",
    "eagle": "ワシ",
    "earphone": "イヤホン",
    "earplug": "耳栓",
    "earring": "イヤリング",
    "easel": "イーゼル",
    "eclair": "エクレア",
    "eel": "ウナギ",
    "egg": "卵",
    "egg roll": "春巻き",
    "egg yolk": "卵黄",
    "eggbeater": "泡立て器",
    "eggplant": "ナス",
    "electric chair": "電気椅子",
    "refrigerator": "冷蔵庫",
    "elephant": "象",
    "elk": "ヘラジカ",
    "envelope": "封筒",
    "eraser": "消しゴム",
    "escargot": "エスカルゴ",
    "eyepatch": "眼帯",
    "falcon": "ハヤブサ",
    "fan": "扇風機",
    "faucet": "蛇口",
    "fedora": "中折れ帽",
    "ferret": "フェレット",
    "ferris wheel": "観覧車",
    "ferry": "フェリー",
    "fig": "いちじく",
    "fighter jet": "戦闘機",
    "figurine": "置物",
    "file cabinet": "書類棚",
    "file": "やすり",
    "fire alarm": "火災報知器",
    "fire engine": "消防車",
    "fire extinguisher": "消火器",
    "fire hose": "消防ホース",
    "fireplace": "暖炉",
    "fireplug": "消火栓",
    "first-aid kit": "救急箱",
    "fish": "魚",
    "fishbowl": "金魚鉢",
    "fishing rod": "釣り竿",
    "flag": "旗",
    "flagpole": "旗竿",
    "flamingo": "フラミンゴ",
    "flannel": "フランネル",
    "flap": "フラップ",
    "flash": "フラッシュ",
    "flashlight": "懐中電灯",
    "fleece": "フリース",
    "flip-flop": "ビーチサンダル",
    "flipper": "足ひれ",
    "flower arrangement": "フラワーアレンジメント",
    "flute glass": "シャンパングラス",
    "foal": "子馬",
    "folding chair": "折りたたみ椅子",
    "food processor": "フードプロセッサー",
    "football": "アメフトボール",
    "football helmet": "アメフトのヘルメット",
    "footstool": "足置き",
    "fork": "フォーク",
    "forklift": "フォークリフト",
    "freight car": "貨車",
    "french toast": "フレンチトースト",
    "freshener": "芳香剤",
    "frisbee": "フリスビー",
    "frog": "カエル",
    "fruit juice": "フルーツジュース",
    "frying pan": "フライパン",
    "fudge": "ファッジ",
    "funnel": "じょうご",
    "futon": "布団",
    "gag": "猿ぐつわ",
    "garbage": "ゴミ",
    "garbage truck": "ゴミ収集車",
    "garden hose": "散水ホース",
    "gargle": "マウスウォッシュ",
    "gargoyle": "ガーゴイル",
    "garlic": "にんにく",
    "gasmask": "ガスマスク",
    "gazelle": "ガゼル",
    "gelatin": "ゼリー",
    "gemstone": "宝石",
    "generator": "発電機",
    "giant panda": "パンダ",
    "gift wrap": "包装紙",
    "ginger": "しょうが",
    "giraffe": "キリン",
    "cincture": "帯",
    "glass": "コップ",
    "globe": "地球儀",
    "glove": "手袋",
    "goat": "ヤギ",
    "goggles": "ゴーグル",
    "goldfish": "金魚",
    "golf club": "ゴルフクラブ",
    "golfcart": "ゴルフカート",
    "gondola": "ゴンドラ",
    "goose": "ガチョウ",
    "gorilla": "ゴリラ",
    "gourd": "ひょうたん",
    "grape": "ぶどう",
    "grater": "おろし金",
    "gravestone": "墓石",
    "gravy boat": "グレイビーソース入れ",
    "green bean": "いんげん",
    "green onion": "ねぎ",
    "griddle": "鉄板",
    "grill": "グリル",
    "grits": "グリッツ",
    "grizzly": "ハイイログマ",
    "grocery bag": "買い物袋",
    "guitar": "ギター",
    "gull": "カモメ",
    "gun": "銃",
    "hairbrush": "ヘアブラシ",
    "hairnet": "ヘアネット",
    "hairpin": "ヘアピン",
    "halter top": "ホルタートップ",
    "ham": "ハム",
    "hamburger": "ハンバーガー",
    "hammer": "ハンマー",
    "hammock": "ハンモック",
    "hamper": "ふた付きかご",
    "hamster": "ハムスター",
    "hair dryer": "ドライヤー",
    "hand glass": "手鏡",
    "hand towel": "ハンドタオル",
    "handcart": "手押し車",
    "handcuff": "手錠",
    "handkerchief": "ハンカチ",
    "handle": "取っ手",
    "handsaw": "のこぎり",
    "hardback book": "ハードカバー本",
    "harmonium": "オルガン",
    "hat": "帽子",
    "hatbox": "帽子箱",
    "veil": "ベール",
    "headband": "ヘアバンド",
    "headboard": "ヘッドボード",
    "headlight": "ヘッドライト",
    "headscarf": "頭のスカーフ",
    "headset": "ヘッドセット",
    "headstall": "馬の頭絡",
    "heart": "ハート",
    "heater": "ヒーター",
    "helicopter": "ヘリコプター",
    "helmet": "ヘルメット",
    "heron": "サギ",
    "highchair": "ベビーチェア",
    "hinge": "蝶番",
    "hippopotamus": "カバ",
    "hockey stick": "ホッケースティック",
    "hog": "豚",
    "home plate": "ホームベース",
    "honey": "はちみつ",
    "fume hood": "レンジフード",
    "hook": "フック",
    "hookah": "水たばこ",
    "hornet": "スズメバチ",
    "horse": "馬",
    "hose": "ホース",
    "hot-air balloon": "熱気球",
    "hotplate": "ホットプレート",
    "hot sauce": "ホットソース",
    "hourglass": "砂時計",
    "houseboat": "屋形船",
    "hummingbird": "ハチドリ",
    "hummus": "フムス",
    "polar bear": "ホッキョクグマ",
    "icecream": "アイスクリーム",
    "popsicle": "アイスキャンディー",
    "ice maker": "製氷機",
    "ice pack": "氷のう",
    "ice skate": "アイススケート靴",
    "igniter": "点火器",
    "inhaler": "吸入器",
    "ipod": "iPod",
    "iron": "アイロン",
    "ironing board": "アイロン台",
    "jacket": "ジャケット",
    "jam": "ジャム",
    "jar": "瓶",
    "jean": "ジーンズ",
    "jeep": "ジープ",
    "jelly bean": "ゼリービーンズ",
    "jersey": "ジャージ",
    "jet plane": "ジェット機",
    "jewel": "宝石",
    "jewelry": "宝飾品",
    "joystick": "ジョイスティック",
    "jumpsuit": "つなぎ服",
    "kayak": "カヤック",
    "keg": "樽",
    "kennel": "犬小屋",
    "kettle": "やかん",
    "key": "鍵",
    "keycard": "カードキー",
    "kilt": "キルト(スカート)",
    "kimono": "着物",
    "kitchen sink": "流し台",
    "kitchen table": "台所のテーブル",
    "kite": "凧",
    "kitten": "子猫",
    "kiwi fruit": "キウイ",
    "knee pad": "膝当て",
    "knife": "ナイフ",
    "knitting needle": "編み針",
    "knob": "つまみ",
    "knocker": "ドアノッカー",
    "koala": "コアラ",
    "lab coat": "白衣",
    "ladder": "はしご",
    "ladle": "お玉",
    "ladybug": "てんとう虫",
    "lamb": "子羊",
    "lamb-chop": "ラムチョップ",
    "lamp": "ランプ",
    "lamppost": "街灯柱",
    "lampshade": "ランプの傘",
    "lantern": "ランタン",
    "lanyard": "ストラップ",
    "laptop computer": "ノートパソコン",
    "lasagna": "ラザニア",
    "latch": "掛け金",
    "lawn mower": "芝刈り機",
    "leather": "革",
    "legging": "レギンス",
    "lego": "レゴ",
    "legume": "豆類",
    "lemon": "レモン",
    "lemonade": "レモネード",
    "lettuce": "レタス",
    "license plate": "ナンバープレート",
    "life buoy": "浮き輪",
    "life jacket": "ライフジャケット",
    "lightbulb": "電球",
    "lightning rod": "避雷針",
    "lime": "ライム",
    "limousine": "リムジン",
    "lion": "ライオン",
    "lip balm": "リップクリーム",
    "liquor": "蒸留酒",
    "lizard": "トカゲ",
    "log": "丸太",
    "lollipop": "ペロペロキャンディ",
    "speaker": "スピーカー",
    "loveseat": "二人掛けソファ",
    "machine gun": "機関銃",
    "magazine": "雑誌",
    "magnet": "磁石",
    "mail slot": "郵便受け口",
    "mailbox": "郵便受け",
    "mallard": "マガモ",
    "mallet": "木槌",
    "mammoth": "マンモス",
    "manatee": "マナティー",
    "mandarin orange": "みかん",
    "manager": "マネージャー",
    "manhole": "マンホール",
    "map": "地図",
    "marker": "マーカー",
    "martini": "マティーニ",
    "mascot": "マスコット",
    "mashed potato": "マッシュポテト",
    "masher": "マッシャー",
    "mask": "マスク",
    "mast": "マスト",
    "mat": "マット",
    "matchbox": "マッチ箱",
    "mattress": "マットレス",
    "measuring cup": "計量カップ",
    "measuring stick": "ものさし",
    "meatball": "ミートボール",
    "medicine": "薬",
    "melon": "メロン",
    "microphone": "マイク",
    "microscope": "顕微鏡",
    "microwave oven": "電子レンジ",
    "milestone": "里程標",
    "milk": "牛乳",
    "milk can": "ミルク缶",
    "milkshake": "ミルクシェイク",
    "minivan": "ミニバン",
    "mint candy": "ミントキャンディ",
    "mirror": "鏡",
    "mitten": "ミトン",
    "mixer": "ミキサー",
    "money": "お金",
    "monitor": "モニター",
    "monkey": "猿",
    "motor": "モーター",
    "motor scooter": "スクーター",
    "motor vehicle": "自動車",
    "motorcycle": "バイク",
    "mound": "マウンド",
    "mouse": "マウス",
    "mousepad": "マウスパッド",
    "muffin": "マフィン",
    "mug": "マグカップ",
    "mushroom": "きのこ",
    "music stool": "ピアノ椅子",
    "musical instrument": "楽器",
    "nailfile": "爪やすり",
    "napkin": "ナプキン",
    "neckerchief": "ネッカチーフ",
    "necklace": "ネックレス",
    "necktie": "ネクタイ",
    "needle": "針",
    "nest": "巣",
    "newspaper": "新聞",
    "newsstand": "新聞売店",
    "nightshirt": "寝間着",
    "nosebag": "飼い葉袋",
    "noseband": "鼻革",
    "notebook": "ノート",
    "notepad": "メモ帳",
    "nut": "ナット",
    "nutcracker": "くるみ割り器",
    "oar": "オール",
    "octopus": "タコ",
    "oil lamp": "オイルランプ",
    "olive oil": "オリーブオイル",
    "omelet": "オムレツ",
    "onion": "玉ねぎ",
    "orange": "オレンジ",
    "orange juice": "オレンジジュース",
    "ostrich": "ダチョウ",
    "ottoman": "オットマン",
    "oven": "オーブン",
    "overalls": "オーバーオール",
    "owl": "フクロウ",
    "packet": "小袋",
    "inkpad": "スタンプ台",
    "pad": "パッド",
    "paddle": "パドル",
    "padlock": "南京錠",
    "paintbrush": "絵筆",
    "painting": "絵画",
    "pajamas": "パジャマ",
    "palette": "パレット",
    "pan": "フライパン",
    "pancake": "パンケーキ",
    "pantyhose": "パンスト",
    "papaya": "パパイヤ",
    "paper plate": "紙皿",
    "paper towel": "ペーパータオル",
    "paperback book": "文庫本",
    "paperweight": "文鎮",
    "parachute": "パラシュート",
    "parakeet": "インコ",
    "parasail": "パラセール",
    "parasol": "日傘",
    "parchment": "羊皮紙",
    "parka": "防寒パーカー",
    "parking meter": "パーキングメーター",
    "parrot": "オウム",
    "passenger car": "客車",
    "passenger ship": "客船",
    "passport": "パスポート",
    "pastry": "ペストリー",
    "patty": "パティ",
    "pea": "えんどう豆",
    "peach": "桃",
    "peanut butter": "ピーナッツバター",
    "pear": "梨",
    "peeler": "皮むき器",
    "wooden leg": "義足",
    "pegboard": "有孔ボード",
    "pelican": "ペリカン",
    "pen": "ペン",
    "pencil": "鉛筆",
    "pencil box": "筆箱",
    "pencil sharpener": "鉛筆削り",
    "pendulum": "振り子",
    "penguin": "ペンギン",
    "pennant": "ペナント",
    "penny": "1セント硬貨",
    "pepper": "こしょう",
    "pepper mill": "こしょう挽き",
    "perfume": "香水",
    "persimmon": "柿",
    "person": "人",
    "pet": "ペット",
    "pew": "教会の長椅子",
    "phonebook": "電話帳",
    "phonograph record": "レコード",
    "piano": "ピアノ",
    "pickle": "ピクルス",
    "pickup truck": "ピックアップトラック",
    "pie": "パイ",
    "pigeon": "ハト",
    "piggy bank": "貯金箱",
    "pillow": "枕",
    "pin": "ピン",
    "pineapple": "パイナップル",
    "pinecone": "松ぼっくり",
    "ping-pong ball": "卓球ボール",
    "pinwheel": "風車(おもちゃ)",
    "tobacco pipe": "たばこパイプ",
    "pipe": "配管",
    "pistol": "拳銃",
    "pita": "ピタパン",
    "pitcher": "水差し",
    "pitchfork": "干し草用フォーク",
    "pizza": "ピザ",
    "place mat": "ランチョンマット",
    "plate": "皿",
    "platter": "大皿",
    "playpen": "ベビーサークル",
    "pliers": "ペンチ",
    "plow": "鋤",
    "plume": "羽飾り",
    "pocket watch": "懐中時計",
    "pocketknife": "折りたたみナイフ",
    "poker": "火かき棒",
    "pole": "柱",
    "polo shirt": "ポロシャツ",
    "poncho": "ポンチョ",
    "pony": "ポニー",
    "pool table": "ビリヤード台",
    "pop": "炭酸飲料",
    "postbox": "郵便ポスト",
    "postcard": "はがき",
    "poster": "ポスター",
    "pot": "鍋",
    "flowerpot": "植木鉢",
    "potato": "じゃがいも",
    "potholder": "鍋つかみ",
    "pottery": "陶器",
    "pouch": "ポーチ",
    "power shovel": "ショベルカー",
    "prawn": "エビ",
    "pretzel": "プレッツェル",
    "printer": "プリンター",
    "projectile": "発射体",
    "projector": "プロジェクター",
    "propeller": "プロペラ",
    "prune": "プルーン",
    "pudding": "プリン",
    "puffer": "フグ",
    "puffin": "ツノメドリ",
    "pug-dog": "パグ",
    "pumpkin": "かぼちゃ",
    "puncher": "穴あけパンチ",
    "puppet": "操り人形",
    "puppy": "子犬",
    "quesadilla": "ケサディーヤ",
    "quiche": "キッシュ",
    "quilt": "キルト布団",
    "rabbit": "ウサギ",
    "race car": "レーシングカー",
    "racket": "ラケット",
    "radar": "レーダー",
    "radiator": "ラジエーター",
    "radio receiver": "ラジオ",
    "radish": "大根",
    "raft": "いかだ",
    "rag doll": "ぬいぐるみ人形",
    "raincoat": "レインコート",
    "ram": "雄羊",
    "raspberry": "ラズベリー",
    "rat": "ネズミ",
    "razorblade": "かみそりの刃",
    "reamer": "果汁絞り器",
    "rearview mirror": "バックミラー",
    "receipt": "レシート",
    "recliner": "リクライニングチェア",
    "record player": "レコードプレーヤー",
    "reflector": "反射板",
    "remote control": "リモコン",
    "rhinoceros": "サイ",
    "rib": "リブ肉",
    "rifle": "ライフル",
    "ring": "指輪",
    "river boat": "川船",
    "road map": "道路地図",
    "robe": "ローブ",
    "rocking chair": "ロッキングチェア",
    "rodent": "げっ歯類",
    "roller skate": "ローラースケート",
    "rollerblade": "インラインスケート",
    "rolling pin": "めん棒",
    "root beer": "ルートビア",
    "router": "ルーター",
    "rubber band": "輪ゴム",
    "runner": "細長いカーペット",
    "plastic bag": "ビニール袋",
    "saddle": "鞍",
    "saddle blanket": "鞍敷き",
    "saddlebag": "サドルバッグ",
    "safety pin": "安全ピン",
    "sail": "帆",
    "salad": "サラダ",
    "salad plate": "サラダ皿",
    "salami": "サラミ",
    "salmon": "サケ",
    "salsa": "サルサ",
    "saltshaker": "塩入れ",
    "sandal": "サンダル",
    "sandwich": "サンドイッチ",
    "satchel": "肩掛けかばん",
    "saucepan": "片手鍋",
    "saucer": "受け皿",
    "sausage": "ソーセージ",
    "sawhorse": "作業台(馬)",
    "saxophone": "サックス",
    "scale": "はかり",
    "scarecrow": "かかし",
    "scarf": "マフラー",
    "school bus": "スクールバス",
    "scissors": "はさみ",
    "scoreboard": "得点板",
    "scraper": "スクレーパー",
    "screwdriver": "ドライバー(工具)",
    "scrubbing brush": "たわし",
    "sculpture": "彫刻",
    "seabird": "海鳥",
    "seahorse": "タツノオトシゴ",
    "seaplane": "水上飛行機",
    "seashell": "貝殻",
    "sewing machine": "ミシン",
    "shaker": "シェーカー",
    "shampoo": "シャンプー",
    "shark": "サメ",
    "sharpener": "研ぎ器",
    "sharpie": "油性マーカー",
    "shaver": "電気シェーバー",
    "shaving cream": "シェービングクリーム",
    "shawl": "ショール",
    "shears": "大ばさみ",
    "sheep": "羊",
    "shepherd dog": "牧羊犬",
    "sherbert": "シャーベット",
    "shield": "盾",
    "shirt": "シャツ",
    "shoe": "靴",
    "shopping bag": "買い物袋",
    "shopping cart": "ショッピングカート",
    "short pants": "半ズボン",
    "shot glass": "ショットグラス",
    "shoulder bag": "ショルダーバッグ",
    "shovel": "シャベル",
    "shower head": "シャワーヘッド",
    "shower cap": "シャワーキャップ",
    "shower curtain": "シャワーカーテン",
    "shredder": "シュレッダー",
    "signboard": "看板",
    "silo": "サイロ",
    "sink": "流し",
    "skateboard": "スケートボード",
    "skewer": "串",
    "ski": "スキー板",
    "ski boot": "スキーブーツ",
    "ski parka": "スキーウェア",
    "ski pole": "ストック",
    "skirt": "スカート",
    "skullcap": "縁なし帽",
    "sled": "そり",
    "sleeping bag": "寝袋",
    "sling": "三角巾",
    "slipper": "スリッパ",
    "smoothie": "スムージー",
    "snake": "ヘビ",
    "snowboard": "スノーボード",
    "snowman": "雪だるま",
    "snowmobile": "スノーモービル",
    "soap": "石鹸",
    "soccer ball": "サッカーボール",
    "sock": "靴下",
    "sofa": "ソファ",
    "softball": "ソフトボール",
    "solar array": "ソーラーパネル",
    "sombrero": "ソンブレロ",
    "soup": "スープ",
    "soup bowl": "スープ皿",
    "soupspoon": "スープスプーン",
    "sour cream": "サワークリーム",
    "soya milk": "豆乳",
    "space shuttle": "スペースシャトル",
    "sparkler": "線香花火",
    "spatula": "フライ返し",
    "spear": "槍",
    "spectacles": "眼鏡",
    "spice rack": "スパイスラック",
    "spider": "クモ",
    "crawfish": "ザリガニ",
    "sponge": "スポンジ",
    "spoon": "スプーン",
    "sportswear": "スポーツウェア",
    "spotlight": "スポットライト",
    "squid": "イカ",
    "squirrel": "リス",
    "stagecoach": "駅馬車",
    "stapler": "ホチキス",
    "starfish": "ヒトデ",
    "statue": "像",
    "steak": "ステーキ",
    "steak knife": "ステーキナイフ",
    "steering wheel": "ハンドル",
    "stepladder": "脚立",
    "step stool": "踏み台",
    "stereo": "ステレオ",
    "stew": "シチュー",
    "stirrer": "マドラー",
    "stirrup": "あぶみ",
    "stool": "スツール",
    "stop sign": "一時停止標識",
    "brake light": "ブレーキランプ",
    "stove": "コンロ",
    "strainer": "こし器",
    "strap": "ストラップ",
    "straw": "ストロー",
    "strawberry": "いちご",
    "street sign": "道路標識",
    "streetlight": "街灯",
    "string cheese": "さけるチーズ",
    "stylus": "スタイラス",
    "subwoofer": "サブウーファー",
    "sugar bowl": "砂糖入れ",
    "sugarcane": "サトウキビ",
    "suit": "スーツ",
    "sunflower": "ひまわり",
    "sunglasses": "サングラス",
    "sunhat": "日よけ帽",
    "surfboard": "サーフボード",
    "sushi": "寿司",
    "mop": "モップ",
    "sweat pants": "スウェットパンツ",
    "sweatband": "汗止めバンド",
    "sweater": "セーター",
    "sweatshirt": "トレーナー",
    "sweet potato": "さつまいも",
    "swimsuit": "水着",
    "sword": "剣",
    "syringe": "注射器",
    "tabasco sauce": "タバスコ",
    "table-tennis table": "卓球台",
    "table": "テーブル",
    "table lamp": "卓上ランプ",
    "tablecloth": "テーブルクロス",
    "tachometer": "回転計",
    "taco": "タコス",
    "tag": "タグ",
    "taillight": "テールランプ",
    "tambourine": "タンバリン",
    "army tank": "戦車",
    "tank": "タンク",
    "tank top": "タンクトップ",
    "tape": "テープ",
    "tape measure": "巻き尺",
    "tapestry": "タペストリー",
    "tarp": "防水シート",
    "tartan": "タータン",
    "tassel": "房飾り",
    "tea bag": "ティーバッグ",
    "teacup": "ティーカップ",
    "teakettle": "ティーケトル",
    "teapot": "ティーポット",
    "teddy bear": "ぬいぐるみのクマ",
    "telephone": "電話",
    "telephone booth": "電話ボックス",
    "telephone pole": "電柱",
    "telephoto lens": "望遠レンズ",
    "television camera": "テレビカメラ",
    "television set": "テレビ",
    "tennis ball": "テニスボール",
    "tennis racket": "テニスラケット",
    "tequila": "テキーラ",
    "thermometer": "体温計",
    "thermos bottle": "魔法瓶",
    "thermostat": "サーモスタット",
    "thimble": "指ぬき",
    "thread": "糸",
    "thumbtack": "画びょう",
    "tiara": "ティアラ",
    "tiger": "トラ",
    "tights": "タイツ",
    "timer": "タイマー",
    "tinfoil": "アルミホイル",
    "tinsel": "モール(装飾)",
    "tissue paper": "ティッシュ",
    "toast": "トースト",
    "toaster": "トースター",
    "toaster oven": "オーブントースター",
    "toilet": "トイレ",
    "toilet tissue": "トイレットペーパー",
    "tomato": "トマト",
    "tongs": "トング",
    "toolbox": "工具箱",
    "toothbrush": "歯ブラシ",
    "toothpaste": "歯磨き粉",
    "toothpick": "つまようじ",
    "cover": "カバー",
    "tortilla": "トルティーヤ",
    "tow truck": "レッカー車",
    "towel": "タオル",
    "towel rack": "タオル掛け",
    "toy": "おもちゃ",
    "tractor": "トラクター",
    "traffic light": "信号機",
    "dirt bike": "オフロードバイク",
    "trailer truck": "トレーラー",
    "train": "電車",
    "trampoline": "トランポリン",
    "tray": "トレー",
    "trench coat": "トレンチコート",
    "triangle": "トライアングル",
    "tricycle": "三輪車",
    "tripod": "三脚",
    "trousers": "ズボン",
    "truck": "トラック",
    "truffle": "トリュフ",
    "trunk": "トランク",
    "vat": "大桶",
    "turban": "ターバン",
    "turkey": "七面鳥",
    "turnip": "かぶ",
    "turtle": "カメ",
    "turtleneck": "タートルネック",
    "typewriter": "タイプライター",
    "umbrella": "傘",
    "underwear": "下着",
    "unicycle": "一輪車",
    "urinal": "小便器",
    "urn": "壺",
    "vacuum cleaner": "掃除機",
    "vase": "花瓶",
    "vending machine": "自動販売機",
    "vent": "通気口",
    "vest": "ベスト",
    "videotape": "ビデオテープ",
    "vinegar": "酢",
    "violin": "バイオリン",
    "vodka": "ウォッカ",
    "volleyball": "バレーボール",
    "vulture": "ハゲワシ",
    "waffle": "ワッフル",
    "waffle iron": "ワッフルメーカー",
    "wagon": "ワゴン",
    "wagon wheel": "車輪",
    "walking stick": "杖",
    "wall clock": "掛け時計",
    "wall socket": "コンセント",
    "wallet": "財布",
    "walrus": "セイウチ",
    "wardrobe": "衣装だんす",
    "washbasin": "洗面台",
    "automatic washer": "洗濯機",
    "watch": "腕時計",
    "water bottle": "水筒",
    "water cooler": "ウォーターサーバー",
    "water faucet": "蛇口",
    "water heater": "給湯器",
    "water jug": "水差し",
    "water gun": "水鉄砲",
    "water scooter": "水上スクーター",
    "water ski": "水上スキー",
    "water tower": "給水塔",
    "watering can": "じょうろ",
    "watermelon": "スイカ",
    "weathervane": "風見鶏",
    "webcam": "ウェブカメラ",
    "wedding cake": "ウェディングケーキ",
    "wedding ring": "結婚指輪",
    "wet suit": "ウェットスーツ",
    "wheel": "車輪",
    "wheelchair": "車椅子",
    "whipped cream": "ホイップクリーム",
    "whistle": "笛",
    "wig": "かつら",
    "wind chime": "風鈴",
    "windmill": "風車",
    "window box": "窓辺の花箱",
    "windshield wiper": "ワイパー",
    "windsock": "吹き流し",
    "wine bottle": "ワインボトル",
    "wine bucket": "ワインクーラー",
    "wineglass": "ワイングラス",
    "blinder": "馬の目隠し",
    "wok": "中華鍋",
    "wolf": "オオカミ",
    "wooden spoon": "木べら",
    "wreath": "リース",
    "wrench": "レンチ",
    "wristband": "リストバンド",
    "wristlet": "リストレット",
    "yacht": "ヨット",
    "yogurt": "ヨーグルト",
    "yoke": "くびき",
    "zebra": "シマウマ",
    "zucchini": "ズッキーニ",
}
