"""
検出ラベル(英語)→日本語の変換。

COCO 80カテゴリは全て対訳を用意。オープン語彙(LVIS等1200+)で辞書に無い語は、
英語のまま返す(=未知語フォールバック)。必要に応じて辞書を追記して拡張できる。
"""
from __future__ import annotations

# COCO 80クラス(Ultralytics yolov8の標準名)→日本語
COCO_JA: dict[str, str] = {
    "person": "人",
    "bicycle": "自転車",
    "car": "車",
    "motorcycle": "バイク",
    "airplane": "飛行機",
    "bus": "バス",
    "train": "電車",
    "truck": "トラック",
    "boat": "ボート",
    "traffic light": "信号機",
    "fire hydrant": "消火栓",
    "stop sign": "一時停止標識",
    "parking meter": "パーキングメーター",
    "bench": "ベンチ",
    "bird": "鳥",
    "cat": "猫",
    "dog": "犬",
    "horse": "馬",
    "sheep": "羊",
    "cow": "牛",
    "elephant": "象",
    "bear": "熊",
    "zebra": "シマウマ",
    "giraffe": "キリン",
    "backpack": "リュック",
    "umbrella": "傘",
    "handbag": "ハンドバッグ",
    "tie": "ネクタイ",
    "suitcase": "スーツケース",
    "frisbee": "フリスビー",
    "skis": "スキー板",
    "snowboard": "スノーボード",
    "sports ball": "ボール",
    "kite": "凧",
    "baseball bat": "バット",
    "baseball glove": "グローブ",
    "skateboard": "スケートボード",
    "surfboard": "サーフボード",
    "tennis racket": "テニスラケット",
    "bottle": "ボトル",
    "wine glass": "ワイングラス",
    "cup": "カップ",
    "fork": "フォーク",
    "knife": "ナイフ",
    "spoon": "スプーン",
    "bowl": "ボウル",
    "banana": "バナナ",
    "apple": "りんご",
    "sandwich": "サンドイッチ",
    "orange": "オレンジ",
    "broccoli": "ブロッコリー",
    "carrot": "にんじん",
    "hot dog": "ホットドッグ",
    "pizza": "ピザ",
    "donut": "ドーナツ",
    "cake": "ケーキ",
    "chair": "椅子",
    "couch": "ソファ",
    "potted plant": "鉢植え",
    "bed": "ベッド",
    "dining table": "テーブル",
    "toilet": "トイレ",
    "tv": "テレビ",
    "laptop": "ノートパソコン",
    "mouse": "マウス",
    "remote": "リモコン",
    "keyboard": "キーボード",
    "cell phone": "携帯電話",
    "microwave": "電子レンジ",
    "oven": "オーブン",
    "toaster": "トースター",
    "sink": "流し台",
    "refrigerator": "冷蔵庫",
    "book": "本",
    "clock": "時計",
    "vase": "花瓶",
    "scissors": "はさみ",
    "teddy bear": "ぬいぐるみ",
    "hair drier": "ドライヤー",
    "toothbrush": "歯ブラシ",
}

# オープン語彙でよく出る一般語の追加対訳(任意。辞書外は英語のまま)
EXTRA_JA: dict[str, str] = {
    "wallet": "財布",
    "watch": "腕時計",
    "ring": "指輪",
    "coin": "硬貨",
    "glasses": "眼鏡",
    "sunglasses": "サングラス",
    "hat": "帽子",
    "cap": "キャップ",
    "shoe": "靴",
    "pen": "ペン",
    "pencil": "鉛筆",
    "cup ": "カップ",
    "mug": "マグカップ",
    "plate": "皿",
    "can": "缶",
    "box": "箱",
    "bag": "バッグ",
    "key": "鍵",
    "card": "カード",
    "earrings": "イヤリング",
    "necklace": "ネックレス",
    "bracelet": "ブレスレット",
    "camera": "カメラ",
    "headphones": "ヘッドホン",
    "tablet": "タブレット",
    "monitor": "モニター",
    "lamp": "ランプ",
    "plant": "植物",
    "flower": "花",
    "towel": "タオル",
    "pillow": "枕",
    "guitar": "ギター",
    "ball": "ボール",
    "doll": "人形",
}

_TABLE: dict[str, str] = {**COCO_JA, **EXTRA_JA}


def to_ja(name: str) -> str:
    """英語ラベルを日本語へ。辞書に無ければ元の英語をそのまま返す。"""
    if not name:
        return name
    return _TABLE.get(name.strip().lower(), name)
